name: build-and-push-image

on:
  push:
    barnches:
      - "*"
    paths:
      - "**.go"
      - "static"
      - ".github/workflows/docker-push.yaml"

jobs:
  build-and-push:
    name: Docker build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: |
          docker build -t delusinonaloptimist/distance-api:latest --build-arg API_KEY=${{ secrets.API_KEY }} --build-arg PORT="8080" .;

      - name: Push image
        run: |
          docker push delusionaloptimist/distance-api:latest
