name: keep repl up

on:
  schedule:
    - cron: '17,47 * * * *'
  workflow_dispatch:

jobs:
  wake_repl_up:
    name: Wake repl up
    runs-on: ubuntu-latest
    steps:
      - name: Curl
        run: |
          curl https://distance-api.delusionaloptim.repl.co/
